<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="36119" started-at="2018-10-30T13:59:27Z" finished-at="2018-10-30T14:00:03Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="36119" started-at="2018-10-30T13:59:27Z" finished-at="2018-10-30T14:00:03Z">
      <class name="testcases.tc_001">
        <test-method status="FAIL" signature="findEmail()[pri:0, instance:testcases.tc_001@44b194fe]" name="findEmail" duration-ms="37" started-at="2018-10-30T19:29:27Z" finished-at="2018-10-30T19:29:27Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at testcases.tc_001.findEmail(tc_001.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- findEmail -->
        <test-method status="PASS" signature="notSelenium()[pri:0, instance:testcases.tc_001@44b194fe]" name="notSelenium" duration-ms="2" started-at="2018-10-30T19:29:27Z" finished-at="2018-10-30T19:29:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- notSelenium -->
        <test-method status="PASS" signature="testcase1()[pri:0, instance:testcases.tc_001@44b194fe]" name="testcase1" duration-ms="36041" started-at="2018-10-30T19:29:27Z" finished-at="2018-10-30T19:30:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase1 -->
      </class> <!-- testcases.tc_001 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
